Update offsets for Skyrim AE 1.6.318
Ryan-rsm-McKenzie/CommonLibSSE pull request #112
Opened 2021-11-15 22:17 UTC by Nukem9

Title.

I had to switch to REL::Offset because an updated version of the address library is not available. There's a script to easily swap between the two so that can be done later. These were all manually translated with BinDiff or direct code signatures.

NiRTTI and RTTI were generated with [powerofthree's SKSE plugin](https://github.com/powerof3/RTTIDumpSE).

Certain functions or RTTI entries don't exist any longer. I don't know how you want to resolve these:
[here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/compare/master...Nukem9:master#diff-9bd04ac9ffb35ca549191281fa321a798c84b00fb0f496231bc9e4bc466933f6R333)
[here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/compare/master...Nukem9:master#diff-9bd04ac9ffb35ca549191281fa321a798c84b00fb0f496231bc9e4bc466933f6R385)
[here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/compare/master...Nukem9:master#diff-9bd04ac9ffb35ca549191281fa321a798c84b00fb0f496231bc9e4bc466933f6R387)
[here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/compare/master...Nukem9:master#diff-9bd04ac9ffb35ca549191281fa321a798c84b00fb0f496231bc9e4bc466933f6R429)
[here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/compare/master...Nukem9:master#diff-47b26e949ef30ea3b793bf37c3e2325ef2ecb07eb0b31dd99158b32c952cbbe9R17)
[removed](include/RE/L/LoggingDisabler.h)

2021-11-15 23:31 UTC, Exit-9B commented
From what I can tell:
`GFxValue::ObjectInterface::GetArraySize`: 0x00F0C310
`InventoryChanges::GetNextUniqueID`: 0x001F87B0 (another function 0x001F8600 looks similar though)
`LooseFileStream::ctor`: Gone, but there are 2 other constructors 0x00C72BF0 and 0x00C72E70
`ScriptEventSourceHolder::SendActivateEvent`: Inlined

`LoggingDisabler`: Renamed to `DejaGFxLogger`

The only one I've actually tested in a plugin is `GetArraySize`. I can confirm that one works.

2021-11-16 01:39 UTC, Ryan-rsm-McKenzie requested changes

2021-11-16 01:39 UTC, Ryan-rsm-McKenzie commented on include/SKSE/Interfaces.h
> +	};
```suggestion
	struct PluginVersionData
	{
	public:
		enum
		{
			kVersion = 1,
		};

		constexpr void AuthorEmail(std::string_view a_email) noexcept { SetCharBuffer(a_email, std::span{ supportEmail }); }
		constexpr void AuthorName(std::string_view a_name) noexcept { SetCharBuffer(a_name, std::span{ author }); }

		constexpr void CompatibleVersions(std::initializer_list<REL::Version> a_versions) noexcept
		{
			assert(a_versions.size() < std::size(compatibleVersions) - 1);
			std::transform(
				a_versions.begin(),
				a_versions.end(),
				std::begin(compatibleVersions),
				[](const REL::Version& a_version) noexcept { return a_version.pack(); });
		}

		constexpr void MinimumRequiredXSEVersion(REL::Version a_version) noexcept { xseMinimum = a_version.pack(); }
		constexpr void PluginName(std::string_view a_plugin) noexcept { SetCharBuffer(a_plugin, std::span{ pluginName }); }
		constexpr void PluginVersion(REL::Version a_version) noexcept { pluginVersion = a_version.pack(); }
		constexpr void UsesAddressLibrary(bool a_value) noexcept { addressLibrary = a_value; }
		constexpr void UsesSigScanning(bool a_value) noexcept { sigScanning = a_value; }

		const std::uint32_t dataVersion{ kVersion };
		std::uint32_t       pluginVersion = 0;
		char                pluginName[256] = {};
		char                author[256] = {};
		char                supportEmail[256] = {};
		union
		{
			struct
			{
				bool addressLibrary: 1;
				bool sigScanning: 1;
			};
			std::uint32_t padding = 0;
		};
		std::uint32_t compatibleVersions[16] = {};
		std::uint32_t xseMinimum = 0;

	private:
		static constexpr void SetCharBuffer(
			std::string_view a_src,
			std::span<char>  a_dst) noexcept
		{
			assert(a_src.size() < a_dst.size());
			std::fill(a_dst.begin(), a_dst.end(), '\0');
			std::copy(a_src.begin(), a_src.end(), a_dst.begin());
		}
	};
	static_assert(offsetof(PluginVersionData, dataVersion) == 0x000);
	static_assert(offsetof(PluginVersionData, pluginVersion) == 0x004);
	static_assert(offsetof(PluginVersionData, pluginName) == 0x008);
	static_assert(offsetof(PluginVersionData, author) == 0x108);
	static_assert(offsetof(PluginVersionData, supportEmail) == 0x208);
	static_assert(offsetof(PluginVersionData, padding) == 0x308);
	static_assert(offsetof(PluginVersionData, compatibleVersions) == 0x30C);
	static_assert(offsetof(PluginVersionData, xseMinimum) == 0x34C);
	static_assert(sizeof(PluginVersionData) == 0x350);
```

2021-11-16 01:39 UTC, Ryan-rsm-McKenzie commented on include/REL/Relocation.h
> +		}
```suggestion
		[[nodiscard]] constexpr std::uint32_t pack() const noexcept
		{
			return static_cast<std::uint32_t>(
				(_impl[0] & 0x0FF) << 24u |
				(_impl[1] & 0x0FF) << 16u |
				(_impl[2] & 0xFFF) << 4u |
				(_impl[3] & 0x00F) << 0u);
		}
```

2021-11-16 01:39 UTC, Ryan-rsm-McKenzie commented on src/SKSE/API.cpp
> +#endif
```suggestion
		(void)REL::Module::get();
		//(void)REL::IDDatabase::get();
```

2021-11-16 02:14 UTC, Ryan-rsm-McKenzie commented
I would comment out the associated function for any offsets that weren't located

2021-11-16 03:15 UTC, Ryan-rsm-McKenzie commented
I would use `#if 0` for commenting out multiple lines

2021-11-16 04:07 UTC, Ryan-rsm-McKenzie approved these changes

2021-11-16 04:10 UTC, merged